name: Build and Deploy Bloggy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        path: 'Bloggy_WorkFlow'
      
    - name: Install dependencies
      run: cd Bloggy_WorkFlow/ORLEANS_CAROUX_NOAH_4AJS && npm install
      
    - name: Build project
      run: cd Bloggy_WorkFlow/bloORLEANS_CAROUX_NOAH_4AJSggy && npm build
      
    - name: Deploy to production
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./Bloggy_WorkFlow/ORLEANS_CAROUX_NOAH_4AJS/build
        user_name: your-username
        user_email: your-email
        commit_message: "Deploy bloggy to production"
